/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as BundleSlugRouteImport } from './routes/bundle.$slug'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminBundlesRouteImport } from './routes/admin.bundles'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminBundlesIndexRouteImport } from './routes/admin.bundles.index'
import { Route as ApiOrdersCreateRouteImport } from './routes/api.orders.create'
import { Route as ApiCouponsValidateRouteImport } from './routes/api.coupons.validate'
import { Route as ApiAdminTestTelegramRouteImport } from './routes/api.admin.test-telegram'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminBundlesNewRouteImport } from './routes/admin.bundles.new'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin.products.$id.edit'
import { Route as AdminBundlesIdEditRouteImport } from './routes/admin.bundles.$id.edit'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleSlugRoute = BundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBundlesRoute = AdminBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminBundlesIndexRoute = AdminBundlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBundlesRoute,
} as any)
const ApiOrdersCreateRoute = ApiOrdersCreateRouteImport.update({
  id: '/api/orders/create',
  path: '/api/orders/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCouponsValidateRoute = ApiCouponsValidateRouteImport.update({
  id: '/api/coupons/validate',
  path: '/api/coupons/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestTelegramRoute = ApiAdminTestTelegramRouteImport.update({
  id: '/api/admin/test-telegram',
  path: '/api/admin/test-telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminBundlesNewRoute = AdminBundlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBundlesRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminBundlesIdEditRoute = AdminBundlesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminBundlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/shop': typeof ShopRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bundles': typeof AdminBundlesRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/promos': typeof AdminPromosRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bundles/new': typeof AdminBundlesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/admin/test-telegram': typeof ApiAdminTestTelegramRoute
  '/api/coupons/validate': typeof ApiCouponsValidateRoute
  '/api/orders/create': typeof ApiOrdersCreateRoute
  '/admin/bundles/': typeof AdminBundlesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/bundles/$id/edit': typeof AdminBundlesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/shop': typeof ShopRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promos': typeof AdminPromosRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bundles/new': typeof AdminBundlesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/admin/test-telegram': typeof ApiAdminTestTelegramRoute
  '/api/coupons/validate': typeof ApiCouponsValidateRoute
  '/api/orders/create': typeof ApiOrdersCreateRoute
  '/admin/bundles': typeof AdminBundlesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/bundles/$id/edit': typeof AdminBundlesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/library': typeof LibraryRoute
  '/shop': typeof ShopRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bundles': typeof AdminBundlesRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/promos': typeof AdminPromosRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bundles/new': typeof AdminBundlesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/admin/test-telegram': typeof ApiAdminTestTelegramRoute
  '/api/coupons/validate': typeof ApiCouponsValidateRoute
  '/api/orders/create': typeof ApiOrdersCreateRoute
  '/admin/bundles/': typeof AdminBundlesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/bundles/$id/edit': typeof AdminBundlesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/library'
    | '/shop'
    | '/admin/banners'
    | '/admin/bundles'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promos'
    | '/bundle/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/bundles/new'
    | '/admin/products/new'
    | '/api/admin/test-telegram'
    | '/api/coupons/validate'
    | '/api/orders/create'
    | '/admin/bundles/'
    | '/admin/products/'
    | '/admin/bundles/$id/edit'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/library'
    | '/shop'
    | '/admin/banners'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/promos'
    | '/bundle/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin'
    | '/admin/bundles/new'
    | '/admin/products/new'
    | '/api/admin/test-telegram'
    | '/api/coupons/validate'
    | '/api/orders/create'
    | '/admin/bundles'
    | '/admin/products'
    | '/admin/bundles/$id/edit'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/library'
    | '/shop'
    | '/admin/banners'
    | '/admin/bundles'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promos'
    | '/bundle/$slug'
    | '/order/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/bundles/new'
    | '/admin/products/new'
    | '/api/admin/test-telegram'
    | '/api/coupons/validate'
    | '/api/orders/create'
    | '/admin/bundles/'
    | '/admin/products/'
    | '/admin/bundles/$id/edit'
    | '/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LibraryRoute: typeof LibraryRoute
  ShopRoute: typeof ShopRoute
  BundleSlugRoute: typeof BundleSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiAdminTestTelegramRoute: typeof ApiAdminTestTelegramRoute
  ApiCouponsValidateRoute: typeof ApiCouponsValidateRoute
  ApiOrdersCreateRoute: typeof ApiOrdersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/$slug': {
      id: '/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/bundle/$slug'
      preLoaderRoute: typeof BundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bundles': {
      id: '/admin/bundles'
      path: '/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AdminBundlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/bundles/': {
      id: '/admin/bundles/'
      path: '/'
      fullPath: '/admin/bundles/'
      preLoaderRoute: typeof AdminBundlesIndexRouteImport
      parentRoute: typeof AdminBundlesRoute
    }
    '/api/orders/create': {
      id: '/api/orders/create'
      path: '/api/orders/create'
      fullPath: '/api/orders/create'
      preLoaderRoute: typeof ApiOrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coupons/validate': {
      id: '/api/coupons/validate'
      path: '/api/coupons/validate'
      fullPath: '/api/coupons/validate'
      preLoaderRoute: typeof ApiCouponsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/test-telegram': {
      id: '/api/admin/test-telegram'
      path: '/api/admin/test-telegram'
      fullPath: '/api/admin/test-telegram'
      preLoaderRoute: typeof ApiAdminTestTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/bundles/new': {
      id: '/admin/bundles/new'
      path: '/new'
      fullPath: '/admin/bundles/new'
      preLoaderRoute: typeof AdminBundlesNewRouteImport
      parentRoute: typeof AdminBundlesRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/bundles/$id/edit': {
      id: '/admin/bundles/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/bundles/$id/edit'
      preLoaderRoute: typeof AdminBundlesIdEditRouteImport
      parentRoute: typeof AdminBundlesRoute
    }
  }
}

interface AdminBundlesRouteChildren {
  AdminBundlesNewRoute: typeof AdminBundlesNewRoute
  AdminBundlesIndexRoute: typeof AdminBundlesIndexRoute
  AdminBundlesIdEditRoute: typeof AdminBundlesIdEditRoute
}

const AdminBundlesRouteChildren: AdminBundlesRouteChildren = {
  AdminBundlesNewRoute: AdminBundlesNewRoute,
  AdminBundlesIndexRoute: AdminBundlesIndexRoute,
  AdminBundlesIdEditRoute: AdminBundlesIdEditRoute,
}

const AdminBundlesRouteWithChildren = AdminBundlesRoute._addFileChildren(
  AdminBundlesRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBundlesRoute: typeof AdminBundlesRouteWithChildren
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminPromosRoute: typeof AdminPromosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminBundlesRoute: AdminBundlesRouteWithChildren,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminPromosRoute: AdminPromosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LibraryRoute: LibraryRoute,
  ShopRoute: ShopRoute,
  BundleSlugRoute: BundleSlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiAdminTestTelegramRoute: ApiAdminTestTelegramRoute,
  ApiCouponsValidateRoute: ApiCouponsValidateRoute,
  ApiOrdersCreateRoute: ApiOrdersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
